### PR TITLE
redsnapper: Remove unneeded "thread" rubygem dependency

### PR DESCRIPTION
**Pull request by cemeyer**
My motivation is that it is not included in FreeBSD ports.

### CODE REVIEW

**Comment by scotchi** [comment]
Hi - this tool is primarily distributed as a Ruby Gem and pulls in its dependencies automatically.  I don't see the point in avoiding using another Ruby Gem...

**Comment by cemeyer** [comment]
Yeah, I can understand that logic.  My admittedly weak arguments for removing it are:

1. For whatever reason — unlike other gems, it is not available in FreeBSD ports.  (And I'm not keen on the gem/pip model of sidestepping the operating system package management system.)

2. The thread/pool gem introduces a relatively large body of code written by pseudonymous authors compared to the relatively small and auditable `redsnapper`.  Given that, and the minimal changes required to not use it, I don't see that it is all that useful as a dependency.

3. In the absence of any other factor, fewer dependencies is better. 

(It really is a minimal change to remove the dependency — check out the diff.  Ruby already provides threads, lists, and thread-safe worker queues.  Most of the diff lines come from moving the body of the thread code rather than functionality changes.)

**Comment by scotchi** [comment]
Sorry, but then I see this as a FreeBSD packaging issue.  It's fine to use your own package system instead of the language's dependency system, but then you'll also need to patch the packages to handle such.

**Comment by cemeyer** [comment]
Sure, it's your choice.  I'll keep it in my fork.

**Pull request closed without merging**
